version: '3'


services:
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./upload:/app/upload
    ports:
      - "80:80"
    restart: always
  python:
    container_name: python
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python/:/app/
    ports:
      - "5000:5000"
    restart: always